### ISSUE TITLE
Battery capacity as input parameter

### ISSUE THREAD

**Issue by humi208** [Optic00/ha-akkusteuerung-sma#1]
Currently charging with 0.2C has a fixed value of 2560W in the Modbus write argument as you may have a HVS 12.8.
For my system 0.2C would be 4.416W as I have a HVM 22.1.

Pls make e.g. charging parameters and so on variable depending on system configuration.

**Comment by Optic00** [comment]
Charging Parameters can be set via Helper. As long as its just an automation i will try to minimize on sensor templates.
