### ISSUE TITLE
Sbs5.0

### ISSUE THREAD

**Issue by vdvmichel** [Optic00/ha-akkusteuerung-sma#2]
How can I install this repo? Ik have already installed SMA solar energy and read all my sma inverters.
I just want to control my sbs5.0 with charge and discharge limits …

**Comment by Skybarks** [comment]
Actually, there is no need to install anything. You can simply copy, adjust, and paste the given scripts and examples into your HA. A German and an English "Walkthrough" are planned and hopefully coming soon. If you need help in adjusting or implementing, you can PM me.

First thing: Back up your system, so if anything goes wrong, you can always fall back. You should start with the `configuration.yaml`, then copy the `sma-se-akku-steuerung.yaml` and try if that works (manual charging/discharging and pausing the battery). One important thing: the "automatik" setting is the SMA default. So if you run into problems, just switch to "automatik". The last step would be setting up the "opti automatik."
 😊
