### ISSUE TITLE
Berechnung der zwei Werte?

### ISSUE THREAD

**Issue by fisch55** [Optic00/ha-akkusteuerung-sma#3]
Kannst du die zwei Sensoren auch noch zur Verfügung stellen?
Das wäre spitze!!!

sensor.house_battery_runtime_raw
sensor.ueberschuss_pv_watt

**Comment by Optic00** [comment]
Hi,
habs hinzugefügt in der Readme. Viel Erfolg!

**Comment by fisch55** [comment]
Super vielen Dank dir !!!! Top Sache
